# loader
color b
echo -e "$(tput setaf 3)
 	 OOOOOOOOOO             \n  OOOOOOOOOOOO     OOO      \n  OOO       OOO    O        \n  OO          OO            \n  		OOO       OOOO      \n  OOOOOOOOOOOO             \n 		OOOOOO     OOOOOO     \n   OOO          OOOO       \n   OOO   	OO         OOO    \n   OOO  OO	           OOO   \n    OOO            OOO      \n     OOOO        OOOO       \n    	   OOOOOOOOOOOO     \n        OOOOOOOO        \n
$(tput sgr0)"
sleep 0.3
clear
echo -e "$(tput setaf 3)
  OOOOOOOOOO      	  	O   OOOOOOOOOOOOOOO            \n OOOOOOOOOOOO        OO	 	OOOOOOOOOOOOOOOOOO         \n OOO       OOO      OOOOOOOOOO      OOOO              \n OO          OO     	OOOOOOO           OO             \n OOO       OOOO			 OOOOOOO                         \n OOOOOOOOOOOO       	 OOOOOOOOO          OO           \n OOOOOO     OOOOOO   OO	  	 OOOOOOOOOOOOOO          \n  OOO          OOOO         OOOOOOOOOOOOOOOOO         \n  OOO            OOO    	  OOOOO        OO            \n  OOO             OOO        O OOOOOOO                 \n   OOO            OOO       	   OOOOOO                 \n    OOOO        OOOO           OOOOOOOOOO       OOO    \n      OOOOOOOOOOOO      	    	OOOOOOOOOOOOOOOOOO     \n       OOOOOOOO	      OOOOOOOOOOOOOO                    \n
$(tput sgr0)"
sleep 0.3
clear
echo -e "$(tput setaf 3)
  OOOOOOOOOO                  OOOOOOOOOOOOOOO       	       OOOOOOO		         \n OOOOOOOOOOOO                OOOOOOOOOOOOOOOOOO          OOOOO   OOOO	         \n OOO       OOO              OOOOOOOOOO      OOOO        OOOO        OOO	       \n OO          OO             OOOOOOO                    OOO            OO	       \n OOO       OOOO              OOOOOOO                 	  OOO            OO 	   \n OOOOOOOOOOOO                OOOOOOOOO                 OOO      OOOO  OO	       \n OOOOOO     OOOOOO           OOOOOOOOOOOOOO            OOOO  OOOO   OOOO 	     \n  OOO          OOOO           OOOOOOOOOOOOOOOOO        OOOOOO        OO 	       \n  OOO            OOO          OOOOO                  	   OOO          OO	     \n  OOO             OOO         OOOOOOO              	     OOO         OO  	     \n   OOO            OOO          OOOOOO                   OO          OO	         \n    OOOO        OOOO           OOOOOOOOOO       OOO     OO         OO	         \n      OOOOOOOOOOOO              OOOOOOOOOOOOOOOOOO   	  OO         OOO 	       \n       OOOOOOOO                   OOOOOOOOOOOOOO      OO           OOO 	       \n
$(tput sgr0)"
sleep 0.3
clear
echo -e "$(tput setaf 3)
  OOOOOOOOOO      	          OOOOOOOOOOOOOOO              OOOOOOO		OO	O    OOOOOOOOOO		         \n OOOOOOOOOOOO        	 OOOOOOOOOOOOOOOOOO          OOOOO   OOOO	 OOOOOOOOOOOOOO  	                 \n OOO       OOO      	OOOOOOOOOO      OOOO        OOOO        OOO	OOOOOOO       OO	                 \n OO          OO     	OOOOOOO                    OOO            OO		OOO			                       \n OOO       OOOO		 OOOOOOO                   OOO            OO 	OOO   		O	                       \n OOOOOOOOOOOO       	 OOOOOOOOO                 OOO      OOOO  OO	 OOO   		OO	                   \n OOOOOO     OOOOOO     	 OOOOOOOOOOOOOO            OOOO  OOOO   OOOO 	 	 OOOOOOOOOOOO		           \n  OOO          OOOO           OOOOOOOOOOOOOOOOO        OOOOOO        OO 	    OOOOOOOOOOOO	         \n  OOO            OOO    	  OOOOO                     OOO          OO	OO             OOOO	           \n  OOO             OOO         OOOOOOO                   OOO         OO  	  	 OO           OOO	      \n   OOO            OOO          OOOOOO                    OO          OO	       OO       OOO	       \n    OOOO        OOOO           OOOOOOOOOO       OOO     OO         OO	  OO      OOOOOO	           \n      OOOOOOOOOOOO      	    OOOOOOOOOOOOOOOOOO     OO         OOO 	  	 OOOOOOOOOOOO		           \n       OOOOOOOO		      OOOOOOOOOOOOOO      OO           OOO 	     OOOOOOOO		                        \n
$(tput sgr0)"
sleep 0.3
clear
echo -e "$(tput setaf 3)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO
$(tput sgr0)"
sleep 1
clear
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO
$(tput sgr0)"
sleep 2
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                                         ══
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                                        ════
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                                       ══════
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                                      ════════
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                                     ══════════
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                                    ════════════
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                                   ══════════════
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                                  ════════════════
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                                 ══════════════════
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                                ════════════════════
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                               ══════════════════════
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                              ════════════════════════
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                             ══════════════════════════
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                            ════════════════════════════
$(tput sgr0)"
sleep 0.1
echo -e "$(tput setaf 6)
  OOOOOOOOOO               OOOOOOOOOOOOOOO              OOOOOOO             OOOOOOOOOO          OOOOOOOOOOOOO\n OOOOOOOOOOOO             OOOOOOOOOOOOOOOOOO          OOOOO   OOOO        OOOOOOOOOOOOOO      OOOO     OO   OOO\n OOO       OOO           OOOOOOOOOO      OOOO        OOOO        OOO     OOOOOOO       OO      OO       OO    OOO\n OO          OO          OOOOOOO                    OOO            OO    OOO                            OO     O\n OOO       OOOO           OOOOOOO                   OOO            OO    OOO                            OOO\n OOOOOOOOOOOO             OOOOOOOOO                 OOO      OOOO  OO     OOO                          OOOO\n OOOOOO     OOOOOO        OOOOOOOOOOOOOO            OOOO  OOOO   OOOO      OOOOOOOOOOOO                OOO\n  OOO          OOOO        OOOOOOOOOOOOOOOOO        OOOOOO        OO         OOOOOOOOOOOO              OOO\n  OOO            OOO       OOOOO                     OOO          OO                  OOOO            OOO\n  OOO             OOO      OOOOOOO                   OOO         OO                    OOO           OOO\n   OOO            OOO       OOOOOO                    OO         OO                    OOO           OOO\n    OOOO        OOOO         OOOOOOOOOO       OOO     OO         OO        OO      OOOOOO           OOO\n      OOOOOOOOOOOO            OOOOOOOOOOOOOOOOOO     OO          OOO        OOOOOOOOOOOO            OOOO\n       OOOOOOOO                 OOOOOOOOOOOOOO      OO            OOO         OOOOOOOO               OO\n
                                           ══════════════════════════════
$(tput sgr0)"
sleep 0.1


